### ISSUE TITLE
NFSU2 Unlimiter V3.0.0.1337 Install Issue using Binary

### ISSUE THREAD

**Issue by iixCarbonxZz** [nlgzrgn/NFSU2Unlimiter#3]
I have run into an issue when attempting to install the unlimiter using binary. I have previously been running V2.0.0.1337 fine alongside Extra Options and Olympic Imports but have tried without Olympic Imports also. The Hoodlum .exe asks me for a disc so I cannot use it although the current .exe I am using is another one I had that has been patched up to 1.2 and I am pretty sure is similar to hoodlum in size but does launch. When patching the .exe in binary I get 200 errors and the result was the extra categories were present but the correct strings did not install for the parts. I have included the error log in this [pastebin](https://pastebin.com/zLse42F6).

**Comment by iixCarbonxZz** [comment]
I figured it out. In my Languages file each .bin also had a .bin.bacc equivalent which was screwing with the script somehow. I deleted them and swapped them with the stock foles from a backup I have and it fixed the errors.

**Comment by iixCarbonxZz** [comment]
It worked once and I tried to install the Fairlady Z mod which made resulted in 3 errors, one of which was 

> File: _Install-AddOn.end, Line: 25
Command: [import override Global\GlobalB.lzc DBModelParts CarParts\FAIRLADYZ.BIN]
Error: Exception of type 'System.OutOfMemoryException' was thrown.

The other 2 were just language errors again but is made the game crash on startup. now I can't get Unlimiter to install correctly without the 200 Language errors no matter which .exe I start with.

**Comment by nlgzrgn** [comment]
Looks like you have used an old version of Binary. Please update it to the latest version from https://www.github.com/SpeedReflect/Binary/releases and try again with vanilla game files.

**Comment by iixCarbonxZz** [comment]
Thanks, That was it. As soon as you told me I updated it. I definitely used this version at one point yesterday as I remember downloading the newest version when I clicked the check for updates button but at some point I must have accidentally reverted to an old one again.
